import type { PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';

interface UnitRow extends RowDataPacket {
  id: number;
}

interface EnsureContext {
  connection: PoolConnection;
  employeeId: number;
  employeeName: string;
  primaryTeamId: number | null;
}

const GROUP_UNIT_CODE_PREFIX = 'GROUP-LEADER-';
const SHIFT_UNIT_CODE_PREFIX = 'SHIFT-LEADER-';

const verifyTeamUnit = async (
  connection: PoolConnection,
  teamUnitId: number,
): Promise<number | null> => {
  if (!teamUnitId) {
    return null;
  }

  const [[unit]] = await connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE id = ?
        AND unit_type = 'TEAM'
        AND is_active = 1
      LIMIT 1`,
    [teamUnitId],
  );

  return unit ? unit.id : null;
};

const ensureGroupUnit = async (
  context: EnsureContext,
): Promise<number | null> => {
  if (!context.primaryTeamId) {
    return null;
  }

  // Ensure the parent Team Unit exists
  const parentUnitId = await verifyTeamUnit(context.connection, context.primaryTeamId);
  if (!parentUnitId) {
    return null;
  }

  const unitCode = `${GROUP_UNIT_CODE_PREFIX}${context.employeeId}`;

  const [[existing]] = await context.connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'GROUP'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );

  const unitName = `${context.employeeName}组`;
  let unitId: number;

  if (existing) {
    unitId = existing.id;
    await context.connection.execute<ResultSetHeader>(
      `UPDATE organization_units
          SET unit_name = ?,
              parent_id = ?,
              is_active = 1,
              metadata = JSON_SET(IFNULL(metadata, JSON_OBJECT()), '$.leaderEmployeeId', ?, '$.teamId', ?, '$.autoGenerated', true)
        WHERE id = ?`,
      [unitName, parentUnitId, context.employeeId, context.primaryTeamId, unitId],
    );
  } else {
    const [result] = await context.connection.execute<ResultSetHeader>(
      `INSERT INTO organization_units
        (parent_id, unit_type, unit_code, unit_name, default_shift_code, sort_order, is_active, metadata)
       VALUES (?, 'GROUP', ?, ?, NULL, 0, 1, JSON_OBJECT('leaderEmployeeId', ?, 'teamId', ?, 'autoGenerated', true))`,
      [parentUnitId, unitCode, unitName, context.employeeId, context.primaryTeamId],
    );
    unitId = result.insertId;
  }

  return unitId;
};

const findExistingGroupUnitId = async (
  connection: PoolConnection,
  employeeId: number,
): Promise<number | null> => {
  const unitCode = `${GROUP_UNIT_CODE_PREFIX}${employeeId}`;
  const [[row]] = await connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'GROUP'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );
  return row ? row.id : null;
};

const ensureShiftUnit = async (
  context: EnsureContext,
  groupUnitId: number | null,
): Promise<number | null> => {
  if (!context.primaryTeamId) {
    return null;
  }

  const fallbackParentId = await verifyTeamUnit(context.connection, context.primaryTeamId);
  if (!fallbackParentId) {
    return null;
  }

  const parentUnitId = groupUnitId ?? fallbackParentId;
  const unitCode = `${SHIFT_UNIT_CODE_PREFIX}${context.employeeId}`;

  const [[existing]] = await context.connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'SHIFT'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );

  const unitName = `${context.employeeName}班`;
  let unitId: number;

  if (existing) {
    unitId = existing.id;
    await context.connection.execute<ResultSetHeader>(
      `UPDATE organization_units
          SET unit_name = ?,
              parent_id = ?,
              is_active = 1,
              metadata = JSON_SET(IFNULL(metadata, JSON_OBJECT()), '$.leaderEmployeeId', ?, '$.teamId', ?, '$.autoGenerated', true)
        WHERE id = ?`,
      [unitName, parentUnitId, context.employeeId, context.primaryTeamId, unitId],
    );
  } else {
    const [result] = await context.connection.execute<ResultSetHeader>(
      `INSERT INTO organization_units
        (parent_id, unit_type, unit_code, unit_name, default_shift_code, sort_order, is_active, metadata)
       VALUES (?, 'SHIFT', ?, ?, NULL, 0, 1, JSON_OBJECT('leaderEmployeeId', ?, 'teamId', ?, 'autoGenerated', true))`,
      [parentUnitId, unitCode, unitName, context.employeeId, context.primaryTeamId],
    );
    unitId = result.insertId;
  }

  return unitId;
};

export const syncGroupStructureForLeader = async (
  connection: PoolConnection,
  input: EnsureContext,
) => {
  if (!input.primaryTeamId) {
    return;
  }

  // Simplified: Only ensure Group Unit if User is Group Leader
  await ensureGroupUnit(input);
};

export const syncShiftStructureForLeader = async (
  connection: PoolConnection,
  input: EnsureContext,
) => {
  if (!input.primaryTeamId) {
    return;
  }

  const groupUnitId = await findExistingGroupUnitId(connection, input.employeeId);
  await ensureShiftUnit(input, groupUnitId);
};
