import type { PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';

interface DepartmentRow extends RowDataPacket {
  id: number;
  parent_id: number | null;
  dept_code: string | null;
  dept_name: string;
}

interface TeamRow extends RowDataPacket {
  id: number;
  team_code: string | null;
  team_name: string;
  department_id: number | null;
}

interface UnitRow extends RowDataPacket {
  id: number;
}

interface EnsureContext {
  connection: PoolConnection;
  employeeId: number;
  employeeName: string;
  primaryTeamId: number | null;
}

interface CacheContext {
  departmentUnits: Map<number, number>;
  teamUnits: Map<number, number>;
}

const GROUP_UNIT_CODE_PREFIX = 'GROUP-LEADER-';
const SHIFT_UNIT_CODE_PREFIX = 'SHIFT-LEADER-';

const createCacheContext = (): CacheContext => ({
  departmentUnits: new Map(),
  teamUnits: new Map(),
});

const ensureDepartmentUnit = async (
  connection: PoolConnection,
  departmentId: number,
  cache: CacheContext,
): Promise<number | null> => {
  if (!departmentId) {
    return null;
  }
  if (cache.departmentUnits.has(departmentId)) {
    return cache.departmentUnits.get(departmentId) ?? null;
  }

  const [[dept]] = await connection.execute<DepartmentRow[]>(
    `SELECT id, parent_id, dept_code, dept_name
       FROM departments
      WHERE id = ?
      LIMIT 1`,
    [departmentId],
  );

  if (!dept) {
    return null;
  }

  const parentUnitId = dept.parent_id ? await ensureDepartmentUnit(connection, dept.parent_id, cache) : null;
  const unitCode = dept.dept_code || `DEPT-${dept.id}`;

  const [[existing]] = await connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'DEPARTMENT'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );

  let unitId: number;

  if (existing) {
    unitId = existing.id;
    await connection.execute<ResultSetHeader>(
      `UPDATE organization_units
          SET unit_name = ?,
              parent_id = ?,
              is_active = 1
        WHERE id = ?`,
      [dept.dept_name, parentUnitId ?? null, unitId],
    );
  } else {
    const [result] = await connection.execute<ResultSetHeader>(
      `INSERT INTO organization_units
        (parent_id, unit_type, unit_code, unit_name, default_shift_code, sort_order, is_active, metadata)
       VALUES (?, 'DEPARTMENT', ?, ?, NULL, 0, 1, JSON_OBJECT('departmentId', ?, 'autoGenerated', true))`,
      [parentUnitId ?? null, unitCode, dept.dept_name, dept.id],
    );
    unitId = result.insertId;
  }

  cache.departmentUnits.set(departmentId, unitId);
  return unitId;
};

const ensureTeamUnit = async (
  connection: PoolConnection,
  teamId: number,
  cache: CacheContext,
): Promise<number | null> => {
  if (!teamId) {
    return null;
  }
  if (cache.teamUnits.has(teamId)) {
    return cache.teamUnits.get(teamId) ?? null;
  }

  const [[team]] = await connection.execute<TeamRow[]>(
    `SELECT id, team_code, team_name, department_id
       FROM teams
      WHERE id = ?
      LIMIT 1`,
    [teamId],
  );

  if (!team) {
    return null;
  }

  const parentUnitId = team.department_id
    ? await ensureDepartmentUnit(connection, team.department_id, cache)
    : null;
  const unitCode = team.team_code || `TEAM-${team.id}`;

  const [[existing]] = await connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'TEAM'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );

  let unitId: number;

  if (existing) {
    unitId = existing.id;
    await connection.execute<ResultSetHeader>(
      `UPDATE organization_units
          SET unit_name = ?,
              parent_id = ?,
              is_active = 1
        WHERE id = ?`,
      [team.team_name, parentUnitId ?? null, unitId],
    );
  } else {
    const [result] = await connection.execute<ResultSetHeader>(
      `INSERT INTO organization_units
        (parent_id, unit_type, unit_code, unit_name, default_shift_code, sort_order, is_active, metadata)
       VALUES (?, 'TEAM', ?, ?, NULL, 0, 1, JSON_OBJECT('teamId', ?, 'departmentId', ?, 'autoGenerated', true))`,
      [parentUnitId ?? null, unitCode, team.team_name, team.id, team.department_id],
    );
    unitId = result.insertId;
  }

  cache.teamUnits.set(teamId, unitId);
  return unitId;
};

const ensureGroupUnit = async (
  context: EnsureContext,
  cache: CacheContext,
): Promise<number | null> => {
  if (!context.primaryTeamId) {
    return null;
  }

  const parentUnitId = await ensureTeamUnit(context.connection, context.primaryTeamId, cache);
  if (!parentUnitId) {
    return null;
  }

  const unitCode = `${GROUP_UNIT_CODE_PREFIX}${context.employeeId}`;

  const [[existing]] = await context.connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'GROUP'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );

  const unitName = `${context.employeeName}组`;
  let unitId: number;

  if (existing) {
    unitId = existing.id;
    await context.connection.execute<ResultSetHeader>(
      `UPDATE organization_units
          SET unit_name = ?,
              parent_id = ?,
              is_active = 1,
              metadata = JSON_SET(IFNULL(metadata, JSON_OBJECT()), '$.leaderEmployeeId', ?, '$.teamId', ?, '$.autoGenerated', true)
        WHERE id = ?`,
      [unitName, parentUnitId ?? null, context.employeeId, context.primaryTeamId, unitId],
    );
  } else {
    const [result] = await context.connection.execute<ResultSetHeader>(
      `INSERT INTO organization_units
        (parent_id, unit_type, unit_code, unit_name, default_shift_code, sort_order, is_active, metadata)
       VALUES (?, 'GROUP', ?, ?, NULL, 0, 1, JSON_OBJECT('leaderEmployeeId', ?, 'teamId', ?, 'autoGenerated', true))`,
      [parentUnitId ?? null, unitCode, unitName, context.employeeId, context.primaryTeamId],
    );
    unitId = result.insertId;
  }

  return unitId;
};

const findExistingGroupUnitId = async (
  connection: PoolConnection,
  employeeId: number,
): Promise<number | null> => {
  const unitCode = `${GROUP_UNIT_CODE_PREFIX}${employeeId}`;
  const [[row]] = await connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'GROUP'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );
  return row ? row.id : null;
};

const ensureShiftUnit = async (
  context: EnsureContext,
  cache: CacheContext,
  groupUnitId: number | null,
): Promise<number | null> => {
  if (!context.primaryTeamId) {
    return null;
  }

  const fallbackParentId = await ensureTeamUnit(context.connection, context.primaryTeamId, cache);
  if (!fallbackParentId) {
    return null;
  }

  const parentUnitId = groupUnitId ?? fallbackParentId;
  const unitCode = `${SHIFT_UNIT_CODE_PREFIX}${context.employeeId}`;

  const [[existing]] = await context.connection.execute<UnitRow[]>(
    `SELECT id
       FROM organization_units
      WHERE unit_type = 'SHIFT'
        AND unit_code = ?
      LIMIT 1`,
    [unitCode],
  );

  const unitName = `${context.employeeName}班`;
  let unitId: number;

  if (existing) {
    unitId = existing.id;
    await context.connection.execute<ResultSetHeader>(
      `UPDATE organization_units
          SET unit_name = ?,
              parent_id = ?,
              is_active = 1,
              metadata = JSON_SET(IFNULL(metadata, JSON_OBJECT()), '$.leaderEmployeeId', ?, '$.teamId', ?, '$.autoGenerated', true)
        WHERE id = ?`,
      [unitName, parentUnitId ?? null, context.employeeId, context.primaryTeamId, unitId],
    );
  } else {
    const [result] = await context.connection.execute<ResultSetHeader>(
      `INSERT INTO organization_units
        (parent_id, unit_type, unit_code, unit_name, default_shift_code, sort_order, is_active, metadata)
       VALUES (?, 'SHIFT', ?, ?, NULL, 0, 1, JSON_OBJECT('leaderEmployeeId', ?, 'teamId', ?, 'autoGenerated', true))`,
      [parentUnitId ?? null, unitCode, unitName, context.employeeId, context.primaryTeamId],
    );
    unitId = result.insertId;
  }

  return unitId;
};

export const syncGroupStructureForLeader = async (
  connection: PoolConnection,
  input: EnsureContext,
) => {
  if (!input.primaryTeamId) {
    return;
  }

  const cache = createCacheContext();
  const groupUnitId = await ensureGroupUnit(input, cache);
  if (!groupUnitId) {
    return;
  }
};

export const syncShiftStructureForLeader = async (
  connection: PoolConnection,
  input: EnsureContext,
) => {
  if (!input.primaryTeamId) {
    return;
  }

  const cache = createCacheContext();
  const groupUnitId = await findExistingGroupUnitId(connection, input.employeeId);
  const shiftUnitId = await ensureShiftUnit(input, cache, groupUnitId);

  if (!shiftUnitId) {
    return;
  }
};
