import type {
  V3MainFlowEdge,
  V3MainFlowNode,
  V3OperationPackage,
  V3TemplateDetail,
  V3TemplateSummary,
  V3TriggerRule,
} from './v3BioprocessTypes';

function cloneValue<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function buildSummary(
  detail: {
    edges: V3MainFlowEdge[];
    nodes: V3MainFlowNode[];
    packages: V3OperationPackage[];
    rules: V3TriggerRule[];
    template: Pick<
      V3TemplateSummary,
      | 'id'
      | 'template_code'
      | 'template_name'
      | 'domain_code'
      | 'equipment_mode_scope'
      | 'description'
    >;
  },
): V3TemplateSummary {
  return {
    ...detail.template,
    node_count: detail.nodes.length,
    trigger_rule_count: detail.rules.length,
    package_count: detail.packages.length,
    main_equipment_codes: [...new Set(detail.nodes.map((node) => node.default_equipment_code).filter(Boolean))] as string[],
  };
}

const susBioreactorSetupPackage: V3OperationPackage = {
  id: 201,
  template_id: null,
  package_code: 'SUS_BIOREACTOR_SETUP',
  package_name: 'SUS 反应器 Setup 包',
  package_type: 'SETUP',
  target_entity_type: 'EQUIPMENT',
  equipment_mode: 'SUS',
  description: '用于 SUS 生物反应器进入 setup 状态的标准操作包。',
  is_reusable: true,
  metadata: {
    state_chain: ['setup'],
  },
  members: [
    {
      id: 2011,
      package_id: 201,
      member_code: 'BAG_INSTALL',
      operation_code: 'SUS-BAG-INSTALL',
      operation_name: '反应袋安装',
      member_order: 1,
      relative_day_offset: -2,
      relative_minute_offset: 540,
      duration_minutes: 120,
      predecessor_member_id: null,
      target_equipment_state: 'setup',
      target_material_state: null,
      metadata: {
        window_label: '培养前第 2 天',
      },
    },
    {
      id: 2012,
      package_id: 201,
      member_code: 'PRESSURE_TEST',
      operation_code: 'SUS-PRESSURE-TEST',
      operation_name: '保压测试',
      member_order: 2,
      relative_day_offset: -1,
      relative_minute_offset: 480,
      duration_minutes: 90,
      predecessor_member_id: 2011,
      target_equipment_state: 'setup',
      target_material_state: null,
      metadata: {
        window_label: '培养前第 1 天上午',
      },
    },
    {
      id: 2013,
      package_id: 201,
      member_code: 'ELECTRODE_INSTALL',
      operation_code: 'SUS-ELECTRODE-INSTALL',
      operation_name: '电极安装',
      member_order: 3,
      relative_day_offset: -1,
      relative_minute_offset: 720,
      duration_minutes: 60,
      predecessor_member_id: 2012,
      target_equipment_state: 'setup',
      target_material_state: null,
      metadata: {
        window_label: '保压测试后',
      },
    },
  ],
};

const mediaFillPackage: V3OperationPackage = {
  id: 202,
  template_id: null,
  package_code: 'MEDIA_FILL_PACKAGE',
  package_name: '培养基灌注包',
  package_type: 'MEDIA_FILL',
  target_entity_type: 'MATERIAL',
  equipment_mode: 'SUS',
  description: '使设备进入 media_holding，并使培养基进入 in_hold 状态。',
  is_reusable: true,
  metadata: {
    state_chain: ['prepared', 'in_hold'],
  },
  members: [
    {
      id: 2021,
      package_id: 202,
      member_code: 'MEDIA_CHARGE',
      operation_code: 'MEDIA-CHARGE',
      operation_name: '培养基灌注',
      member_order: 1,
      relative_day_offset: -1,
      relative_minute_offset: 900,
      duration_minutes: 180,
      predecessor_member_id: null,
      target_equipment_state: 'media_holding',
      target_material_state: 'prepared',
      metadata: {
        window_label: '接种前完成灌注',
      },
    },
    {
      id: 2022,
      package_id: 202,
      member_code: 'MEDIA_HOLD_RELEASE',
      operation_code: 'MEDIA-HOLD-RELEASE',
      operation_name: '培养基保温确认',
      member_order: 2,
      relative_day_offset: -1,
      relative_minute_offset: 1140,
      duration_minutes: 30,
      predecessor_member_id: 2021,
      target_equipment_state: 'media_holding',
      target_material_state: 'in_hold',
      metadata: {
        window_label: '灌注完成后进入 hold',
      },
    },
  ],
};

const ssCipSipPackage: V3OperationPackage = {
  id: 203,
  template_id: null,
  package_code: 'SS_CIP_SIP_PACKAGE',
  package_name: 'SS CIP/SIP 包',
  package_type: 'CIP_SIP',
  target_entity_type: 'EQUIPMENT',
  equipment_mode: 'SS',
  description: '用于 SS 设备进入 clean_hold 的标准清洗灭菌包。',
  is_reusable: true,
  metadata: {
    state_chain: ['cleaning_cip', 'sterilizing_sip', 'clean_hold'],
  },
  members: [
    {
      id: 2031,
      package_id: 203,
      member_code: 'PRE_RINSE',
      operation_code: 'SS-PRE-RINSE',
      operation_name: '预冲洗',
      member_order: 1,
      relative_day_offset: -1,
      relative_minute_offset: 360,
      duration_minutes: 60,
      predecessor_member_id: null,
      target_equipment_state: 'cleaning_cip',
      target_material_state: null,
      metadata: {
        window_label: '批前一天清晨',
      },
    },
    {
      id: 2032,
      package_id: 203,
      member_code: 'CIP_CYCLE',
      operation_code: 'SS-CIP',
      operation_name: 'CIP',
      member_order: 2,
      relative_day_offset: -1,
      relative_minute_offset: 450,
      duration_minutes: 120,
      predecessor_member_id: 2031,
      target_equipment_state: 'cleaning_cip',
      target_material_state: null,
      metadata: {
        window_label: '预冲洗后',
      },
    },
    {
      id: 2033,
      package_id: 203,
      member_code: 'SIP_CYCLE',
      operation_code: 'SS-SIP',
      operation_name: 'SIP',
      member_order: 3,
      relative_day_offset: -1,
      relative_minute_offset: 600,
      duration_minutes: 90,
      predecessor_member_id: 2032,
      target_equipment_state: 'sterilizing_sip',
      target_material_state: null,
      metadata: {
        window_label: 'CIP 后',
      },
    },
    {
      id: 2034,
      package_id: 203,
      member_code: 'CLEAN_HOLD_RELEASE',
      operation_code: 'SS-CLEAN-HOLD',
      operation_name: 'clean hold 确认',
      member_order: 4,
      relative_day_offset: -1,
      relative_minute_offset: 720,
      duration_minutes: 15,
      predecessor_member_id: 2033,
      target_equipment_state: 'clean_hold',
      target_material_state: null,
      metadata: {
        window_label: 'SIP 完成后',
      },
    },
  ],
};

const bufferTankSetupPackage: V3OperationPackage = {
  id: 204,
  template_id: null,
  package_code: 'BUFFER_TANK_SETUP_PACKAGE',
  package_name: '配液罐 Setup 包',
  package_type: 'SETUP',
  target_entity_type: 'EQUIPMENT',
  equipment_mode: 'SS',
  description: '用于配液罐 / buffer tank 的安装与完整性确认。',
  is_reusable: true,
  metadata: {
    state_chain: ['setup'],
  },
  members: [
    {
      id: 2041,
      package_id: 204,
      member_code: 'TANK_ASSEMBLY',
      operation_code: 'BUF-TANK-ASSEMBLY',
      operation_name: '配液罐安装',
      member_order: 1,
      relative_day_offset: -1,
      relative_minute_offset: 480,
      duration_minutes: 90,
      predecessor_member_id: null,
      target_equipment_state: 'setup',
      target_material_state: null,
      metadata: {
        window_label: '配液前一天',
      },
    },
    {
      id: 2042,
      package_id: 204,
      member_code: 'LINE_INTEGRITY_CHECK',
      operation_code: 'BUF-LINE-CHECK',
      operation_name: '流路完整性确认',
      member_order: 2,
      relative_day_offset: -1,
      relative_minute_offset: 660,
      duration_minutes: 45,
      predecessor_member_id: 2041,
      target_equipment_state: 'setup',
      target_material_state: null,
      metadata: {
        window_label: '安装后',
      },
    },
  ],
};

const uspNodes: V3MainFlowNode[] = [
  {
    id: 11,
    template_id: 1,
    node_key: 'CELL_THAW',
    semantic_key: 'CELL_THAW',
    display_name: '细胞复苏',
    phase_code: 'USP',
    equipment_mode: 'SUS',
    default_duration_minutes: 60,
    sequence_order: 1,
    default_equipment_code: 'SUS-SEED-01',
    default_material_code: null,
    metadata: {
      target_equipment_state: 'processing',
    },
  },
  {
    id: 12,
    template_id: 1,
    node_key: 'INOCULATION',
    semantic_key: 'INOCULATION',
    display_name: '接种',
    phase_code: 'USP',
    equipment_mode: 'SUS',
    default_duration_minutes: 120,
    sequence_order: 2,
    default_equipment_code: 'SUS-BR-01',
    default_material_code: null,
    metadata: {
      target_equipment_state: 'processing',
    },
  },
  {
    id: 13,
    template_id: 1,
    node_key: 'CELL_CULTURE',
    semantic_key: 'CELL_CULTURE',
    display_name: '细胞培养',
    phase_code: 'USP',
    equipment_mode: 'SUS',
    default_duration_minutes: 5760,
    sequence_order: 3,
    default_equipment_code: 'SUS-BR-01',
    default_material_code: 'MEDIA-A',
    metadata: {
      required_equipment_state: 'processing',
      required_material_state: 'in_hold',
    },
  },
  {
    id: 14,
    template_id: 1,
    node_key: 'PASSAGE',
    semantic_key: 'PASSAGE',
    display_name: '转种',
    phase_code: 'USP',
    equipment_mode: 'SUS',
    default_duration_minutes: 150,
    sequence_order: 4,
    default_equipment_code: 'SUS-BR-01',
    default_material_code: null,
    metadata: {
      target_equipment_state: 'processing',
    },
  },
  {
    id: 15,
    template_id: 1,
    node_key: 'HARVEST',
    semantic_key: 'HARVEST',
    display_name: '收获',
    phase_code: 'USP',
    equipment_mode: 'SS',
    default_duration_minutes: 180,
    sequence_order: 5,
    default_equipment_code: 'SS-HARV-01',
    default_material_code: null,
    metadata: {
      target_equipment_state: 'processing',
    },
  },
];

const uspEdges: V3MainFlowEdge[] = [
  {
    predecessor_node_id: 11,
    successor_node_id: 12,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 60,
  },
  {
    predecessor_node_id: 12,
    successor_node_id: 13,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 0,
  },
  {
    predecessor_node_id: 13,
    successor_node_id: 14,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 0,
  },
  {
    predecessor_node_id: 14,
    successor_node_id: 15,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 120,
  },
];

const uspRules: V3TriggerRule[] = [
  {
    id: 101,
    template_id: 1,
    rule_code: 'USP_SETUP_BEFORE_CULTURE',
    target_node_id: 13,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'PACKAGE_BEFORE_START',
    operation_code: null,
    operation_name: null,
    operation_role: 'AUXILIARY',
    default_duration_minutes: 0,
    earliest_offset_minutes: null,
    recommended_offset_minutes: null,
    latest_offset_minutes: null,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: 201,
    target_equipment_state: 'setup',
    target_material_state: null,
    is_blocking: true,
    sort_order: 10,
    metadata: {
      purpose: '达到 setup 状态后才能培养基灌注',
    },
  },
  {
    id: 102,
    template_id: 1,
    rule_code: 'USP_MEDIA_FILL_BEFORE_CULTURE',
    target_node_id: 13,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'PACKAGE_BEFORE_START',
    operation_code: null,
    operation_name: null,
    operation_role: 'AUXILIARY',
    default_duration_minutes: 0,
    earliest_offset_minutes: null,
    recommended_offset_minutes: null,
    latest_offset_minutes: null,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: 202,
    target_equipment_state: 'media_holding',
    target_material_state: 'in_hold',
    is_blocking: true,
    sort_order: 20,
    metadata: {
      hold_window_hours: 24,
      purpose: '培养前需处于 media_holding',
    },
  },
  {
    id: 103,
    template_id: 1,
    rule_code: 'USP_FIRST_SAMPLE',
    target_node_id: 11,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'WINDOW',
    operation_code: 'USP-SAMPLE-FIRST',
    operation_name: '首次取样',
    operation_role: 'AUXILIARY',
    default_duration_minutes: 20,
    earliest_offset_minutes: 0,
    recommended_offset_minutes: 60,
    latest_offset_minutes: 120,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: null,
    target_equipment_state: null,
    target_material_state: null,
    is_blocking: false,
    sort_order: 30,
    metadata: {
      window_label: '复苏开始后 2 小时内',
    },
  },
  {
    id: 104,
    template_id: 1,
    rule_code: 'USP_DAILY_SAMPLE',
    target_node_id: 12,
    anchor_mode: 'NODE_END',
    anchor_ref_code: null,
    trigger_mode: 'RECURRING_WINDOW',
    operation_code: 'USP-SAMPLE-DAILY',
    operation_name: '日常取样',
    operation_role: 'AUXILIARY',
    default_duration_minutes: 20,
    earliest_offset_minutes: 960,
    recommended_offset_minutes: 1440,
    latest_offset_minutes: 1920,
    repeat_every_minutes: 1440,
    repeat_until_node_id: 14,
    dependency_rule_code: null,
    generator_package_id: null,
    target_equipment_state: null,
    target_material_state: null,
    is_blocking: false,
    sort_order: 40,
    metadata: {
      window_label: '接种完成后每日 ±8h',
    },
  },
  {
    id: 105,
    template_id: 1,
    rule_code: 'USP_FEED_AFTER_SAMPLE',
    target_node_id: 13,
    anchor_mode: 'RULE_END',
    anchor_ref_code: 'USP_DAILY_SAMPLE',
    trigger_mode: 'FOLLOW_DEPENDENCY',
    operation_code: 'USP-FEED',
    operation_name: '补料',
    operation_role: 'AUXILIARY',
    default_duration_minutes: 45,
    earliest_offset_minutes: 30,
    recommended_offset_minutes: 60,
    latest_offset_minutes: 180,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: 'USP_DAILY_SAMPLE',
    generator_package_id: null,
    target_equipment_state: null,
    target_material_state: null,
    is_blocking: false,
    sort_order: 50,
    metadata: {
      dependency: 'after_sample',
    },
  },
  {
    id: 106,
    template_id: 1,
    rule_code: 'USP_PROCESSING_GATE',
    target_node_id: 13,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'STATE_GATE',
    operation_code: null,
    operation_name: null,
    operation_role: 'AUXILIARY',
    default_duration_minutes: 0,
    earliest_offset_minutes: null,
    recommended_offset_minutes: null,
    latest_offset_minutes: null,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: null,
    target_equipment_state: 'processing',
    target_material_state: 'in_hold',
    is_blocking: true,
    sort_order: 60,
    metadata: {
      purpose: '进入 processing 前必须满足设备态和物料态',
    },
  },
];

const dspNodes: V3MainFlowNode[] = [
  {
    id: 21,
    template_id: 2,
    node_key: 'LOAD_COLUMN',
    semantic_key: 'LOAD_COLUMN',
    display_name: '上柱',
    phase_code: 'DSP',
    equipment_mode: 'SS',
    default_duration_minutes: 240,
    sequence_order: 1,
    default_equipment_code: 'SS-CHROM-01',
    default_material_code: 'BUF-EQ-01',
    metadata: {
      required_equipment_state: 'clean_hold',
    },
  },
  {
    id: 22,
    template_id: 2,
    node_key: 'WASH_COLUMN',
    semantic_key: 'WASH_COLUMN',
    display_name: '洗柱',
    phase_code: 'DSP',
    equipment_mode: 'SS',
    default_duration_minutes: 60,
    sequence_order: 2,
    default_equipment_code: 'SS-CHROM-01',
    default_material_code: 'BUF-EQ-01',
    metadata: {
      target_equipment_state: 'processing',
    },
  },
  {
    id: 23,
    template_id: 2,
    node_key: 'ELUTE_PRODUCT',
    semantic_key: 'ELUTE_PRODUCT',
    display_name: '洗脱',
    phase_code: 'DSP',
    equipment_mode: 'SS',
    default_duration_minutes: 90,
    sequence_order: 3,
    default_equipment_code: 'SS-CHROM-01',
    default_material_code: 'BUF-EQ-01',
    metadata: {
      target_equipment_state: 'processing',
    },
  },
];

const dspEdges: V3MainFlowEdge[] = [
  {
    predecessor_node_id: 21,
    successor_node_id: 22,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 0,
  },
  {
    predecessor_node_id: 22,
    successor_node_id: 23,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 0,
  },
];

const dspRules: V3TriggerRule[] = [
  {
    id: 201,
    template_id: 2,
    rule_code: 'DSP_CIP_SIP_BEFORE_LOAD',
    target_node_id: 21,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'PACKAGE_BEFORE_START',
    operation_code: null,
    operation_name: null,
    operation_role: 'AUXILIARY',
    default_duration_minutes: 0,
    earliest_offset_minutes: null,
    recommended_offset_minutes: null,
    latest_offset_minutes: null,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: 203,
    target_equipment_state: 'clean_hold',
    target_material_state: null,
    is_blocking: true,
    sort_order: 10,
    metadata: {
      purpose: '上柱前需处于 clean_hold',
    },
  },
  {
    id: 202,
    template_id: 2,
    rule_code: 'DSP_LOAD_QC_SAMPLE',
    target_node_id: 21,
    anchor_mode: 'NODE_END',
    anchor_ref_code: null,
    trigger_mode: 'WINDOW',
    operation_code: 'DSP-INPROC-SAMPLE',
    operation_name: '层析中控取样',
    operation_role: 'AUXILIARY',
    default_duration_minutes: 15,
    earliest_offset_minutes: 0,
    recommended_offset_minutes: 30,
    latest_offset_minutes: 90,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: null,
    target_equipment_state: null,
    target_material_state: null,
    is_blocking: false,
    sort_order: 20,
    metadata: {
      window_label: '上柱后 90 分钟内',
    },
  },
];

const spiNodes: V3MainFlowNode[] = [
  {
    id: 31,
    template_id: 3,
    node_key: 'MEDIA_PREP',
    semantic_key: 'MEDIA_PREP',
    display_name: '培养基制备',
    phase_code: 'SPI',
    equipment_mode: 'SS',
    default_duration_minutes: 180,
    sequence_order: 1,
    default_equipment_code: 'SS-BUF-01',
    default_material_code: 'MEDIA-PREP-01',
    metadata: {
      target_material_state: 'prepared',
    },
  },
  {
    id: 32,
    template_id: 3,
    node_key: 'MEDIA_RELEASE',
    semantic_key: 'MEDIA_RELEASE',
    display_name: '培养基放行',
    phase_code: 'SPI',
    equipment_mode: 'SS',
    default_duration_minutes: 30,
    sequence_order: 2,
    default_equipment_code: 'SS-BUF-01',
    default_material_code: 'MEDIA-PREP-01',
    metadata: {
      required_material_state: 'in_hold',
    },
  },
];

const spiEdges: V3MainFlowEdge[] = [
  {
    predecessor_node_id: 31,
    successor_node_id: 32,
    relationship_type: 'FINISH_START',
    min_offset_minutes: 0,
  },
];

const spiRules: V3TriggerRule[] = [
  {
    id: 301,
    template_id: 3,
    rule_code: 'SPI_BUFFER_SETUP_BEFORE_PREP',
    target_node_id: 31,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'PACKAGE_BEFORE_START',
    operation_code: null,
    operation_name: null,
    operation_role: 'AUXILIARY',
    default_duration_minutes: 0,
    earliest_offset_minutes: null,
    recommended_offset_minutes: null,
    latest_offset_minutes: null,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: 204,
    target_equipment_state: 'setup',
    target_material_state: null,
    is_blocking: true,
    sort_order: 10,
    metadata: {
      purpose: '配液前需完成 setup',
    },
  },
  {
    id: 302,
    template_id: 3,
    rule_code: 'SPI_MEDIA_HOLD_GATE',
    target_node_id: 32,
    anchor_mode: 'NODE_START',
    anchor_ref_code: null,
    trigger_mode: 'STATE_GATE',
    operation_code: null,
    operation_name: null,
    operation_role: 'AUXILIARY',
    default_duration_minutes: 0,
    earliest_offset_minutes: null,
    recommended_offset_minutes: null,
    latest_offset_minutes: null,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: null,
    target_equipment_state: 'media_holding',
    target_material_state: 'in_hold',
    is_blocking: true,
    sort_order: 20,
    metadata: {
      purpose: '放行前需处于 media_holding / in_hold',
    },
  },
  {
    id: 303,
    template_id: 3,
    rule_code: 'SPI_MEDIA_SAMPLE',
    target_node_id: 31,
    anchor_mode: 'NODE_END',
    anchor_ref_code: null,
    trigger_mode: 'WINDOW',
    operation_code: 'SPI-MEDIA-SAMPLE',
    operation_name: '培养基取样',
    operation_role: 'AUXILIARY',
    default_duration_minutes: 15,
    earliest_offset_minutes: 0,
    recommended_offset_minutes: 30,
    latest_offset_minutes: 120,
    repeat_every_minutes: null,
    repeat_until_node_id: null,
    dependency_rule_code: null,
    generator_package_id: null,
    target_equipment_state: null,
    target_material_state: null,
    is_blocking: false,
    sort_order: 30,
    metadata: {
      window_label: '制备完成后 2 小时内',
    },
  },
];

const fallbackTemplateDetails: V3TemplateDetail[] = [
  {
    template: buildSummary({
      template: {
        id: 1,
        template_code: 'USP_UPSTREAM_CULTURE_V3',
        template_name: 'USP 上游细胞培养 V3 试点',
        domain_code: 'USP',
        equipment_mode_scope: 'MIXED',
        description: '从细胞复苏到收获的主工艺流，使用触发规则派生取样、补料、setup 和培养基灌注。',
      },
      nodes: uspNodes,
      edges: uspEdges,
      rules: uspRules,
      packages: [susBioreactorSetupPackage, mediaFillPackage],
    }),
    nodes: uspNodes,
    edges: uspEdges,
    rules: uspRules,
    packages: [susBioreactorSetupPackage, mediaFillPackage],
    storage_mode: 'fallback',
  },
  {
    template: buildSummary({
      template: {
        id: 2,
        template_code: 'DSP_CAPTURE_SS_V3',
        template_name: 'DSP 层析捕获 V3 试点',
        domain_code: 'DSP',
        equipment_mode_scope: 'SS',
        description: '代表性 SS 下游流程，验证 CIP/SIP 包与 clean hold 状态链。',
      },
      nodes: dspNodes,
      edges: dspEdges,
      rules: dspRules,
      packages: [ssCipSipPackage],
    }),
    nodes: dspNodes,
    edges: dspEdges,
    rules: dspRules,
    packages: [ssCipSipPackage],
    storage_mode: 'fallback',
  },
  {
    template: buildSummary({
      template: {
        id: 3,
        template_code: 'SPI_MEDIA_PREP_V3',
        template_name: '配液 / 培养基制备 V3 试点',
        domain_code: 'SPI',
        equipment_mode_scope: 'SS',
        description: '验证物料态 prepared / in_hold 与设备态 media_holding 的耦合。',
      },
      nodes: spiNodes,
      edges: spiEdges,
      rules: spiRules,
      packages: [bufferTankSetupPackage],
    }),
    nodes: spiNodes,
    edges: spiEdges,
    rules: spiRules,
    packages: [bufferTankSetupPackage],
    storage_mode: 'fallback',
  },
];

export function getFallbackV3TemplateSummaries(): V3TemplateSummary[] {
  return cloneValue(fallbackTemplateDetails.map((detail) => detail.template));
}

export function getFallbackV3TemplateDetail(templateId: number): V3TemplateDetail | null {
  const detail = fallbackTemplateDetails.find((candidate) => candidate.template.id === templateId);
  return detail ? cloneValue(detail) : null;
}
