-- =====================================================
-- Phase 1: Multi-Team Support Migration
-- 多部门工艺流程支持数据库迁移
-- =====================================================
-- 1. 新增 DSP 和 SP&I 团队到 organization_units
-- 注意：假设 MFG8 的 id=1，USP 的 id=2
INSERT INTO organization_units (
        parent_id,
        unit_type,
        unit_code,
        unit_name,
        sort_order,
        is_active,
        metadata
    )
VALUES (
        1,
        'TEAM',
        'DSP',
        'DSP',
        1,
        1,
        '{"autoGenerated": false}'
    ),
    (
        1,
        'TEAM',
        'SPI',
        'SP&I',
        2,
        1,
        '{"autoGenerated": false}'
    );
-- 2. 创建操作类型配置表
CREATE TABLE IF NOT EXISTS operation_types (
    id INT PRIMARY KEY AUTO_INCREMENT,
    type_code VARCHAR(20) NOT NULL UNIQUE,
    type_name VARCHAR(50) NOT NULL,
    team_id INT NOT NULL,
    color VARCHAR(7) DEFAULT '#1890ff',
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES organization_units(id)
);
-- 3. 插入 USP 上游操作类型
INSERT INTO operation_types (
        type_code,
        type_name,
        team_id,
        color,
        display_order
    )
SELECT type_code,
    type_name,
    ou.id,
    color,
    display_order
FROM (
        SELECT 'CELL_THAW' as type_code,
            '细胞复苏' as type_name,
            '#52c41a' as color,
            1 as display_order
        UNION ALL
        SELECT 'CELL_EXPAND',
            '细胞扩增',
            '#73d13d',
            2
        UNION ALL
        SELECT 'SEED_TRAIN',
            '种子培养',
            '#95de64',
            3
        UNION ALL
        SELECT 'BIOREACTOR_PREP',
            '反应器准备',
            '#1890ff',
            4
        UNION ALL
        SELECT 'INOCULATION',
            '接种',
            '#40a9ff',
            5
        UNION ALL
        SELECT 'CELL_CULTURE',
            '细胞培养',
            '#69c0ff',
            6
        UNION ALL
        SELECT 'FEEDING',
            '补料',
            '#91d5ff',
            7
        UNION ALL
        SELECT 'SAMPLING',
            '取样',
            '#faad14',
            8
        UNION ALL
        SELECT 'MONITORING',
            '在线监控',
            '#ffc53d',
            9
        UNION ALL
        SELECT 'HARVEST',
            '收获',
            '#f5222d',
            10
        UNION ALL
        SELECT 'CIP',
            '原位清洗',
            '#8c8c8c',
            11
        UNION ALL
        SELECT 'SIP',
            '原位灭菌',
            '#595959',
            12
    ) t,
    organization_units ou
WHERE ou.unit_code = 'USP';
-- 4. 插入 DSP 下游操作类型
INSERT INTO operation_types (
        type_code,
        type_name,
        team_id,
        color,
        display_order
    )
SELECT type_code,
    type_name,
    ou.id,
    color,
    display_order
FROM (
        SELECT 'CLARIFICATION' as type_code,
            '澄清' as type_name,
            '#13c2c2' as color,
            1 as display_order
        UNION ALL
        SELECT 'DEPTH_FILTRATION',
            '深层过滤',
            '#36cfc9',
            2
        UNION ALL
        SELECT 'AFFINITY_CHROM',
            '亲和层析',
            '#2f54eb',
            3
        UNION ALL
        SELECT 'ION_EXCHANGE',
            '离子交换层析',
            '#597ef7',
            4
        UNION ALL
        SELECT 'HIC',
            '疏水层析',
            '#85a5ff',
            5
        UNION ALL
        SELECT 'SEC',
            '凝胶过滤层析',
            '#adc6ff',
            6
        UNION ALL
        SELECT 'VIRAL_INACT',
            '病毒灭活',
            '#eb2f96',
            7
        UNION ALL
        SELECT 'VIRAL_FILT',
            '病毒过滤',
            '#f759ab',
            8
        UNION ALL
        SELECT 'UF_DF',
            '超滤/透析',
            '#722ed1',
            9
        UNION ALL
        SELECT 'CONCENTRATION',
            '浓缩',
            '#9254de',
            10
        UNION ALL
        SELECT 'FORMULATION',
            '制剂配制',
            '#b37feb',
            11
        UNION ALL
        SELECT 'STERILE_FILT',
            '除菌过滤',
            '#d3adf7',
            12
        UNION ALL
        SELECT 'FILLING',
            '灌装',
            '#f5222d',
            13
    ) t,
    organization_units ou
WHERE ou.unit_code = 'DSP';
-- 5. 插入 SP&I 配液与器具操作类型
INSERT INTO operation_types (
        type_code,
        type_name,
        team_id,
        color,
        display_order
    )
SELECT type_code,
    type_name,
    ou.id,
    color,
    display_order
FROM (
        SELECT 'BUFFER_PREP' as type_code,
            '缓冲液配制' as type_name,
            '#1890ff' as color,
            1 as display_order
        UNION ALL
        SELECT 'MEDIA_PREP',
            '培养基配制',
            '#40a9ff',
            2
        UNION ALL
        SELECT 'REAGENT_PREP',
            '试剂配制',
            '#69c0ff',
            3
        UNION ALL
        SELECT 'SOLUTION_QC',
            '溶液质检',
            '#faad14',
            4
        UNION ALL
        SELECT 'WEIGHING',
            '称量',
            '#52c41a',
            5
        UNION ALL
        SELECT 'PH_ADJUST',
            'pH调节',
            '#73d13d',
            6
        UNION ALL
        SELECT 'STERILE_FILT_SPI',
            '除菌过滤',
            '#722ed1',
            7
        UNION ALL
        SELECT 'DISPENSING',
            '分装',
            '#9254de',
            8
        UNION ALL
        SELECT 'AUTOCLAVE',
            '高压灭菌',
            '#f5222d',
            9
        UNION ALL
        SELECT 'EQUIPMENT_PREP',
            '器具准备',
            '#8c8c8c',
            10
        UNION ALL
        SELECT 'EQUIPMENT_CLEAN',
            '器具清洗',
            '#595959',
            11
        UNION ALL
        SELECT 'STORAGE',
            '储存管理',
            '#434343',
            12
    ) t,
    organization_units ou
WHERE ou.unit_code = 'SPI';
-- 6. 为 process_templates 添加 team_id 外键
ALTER TABLE process_templates
ADD COLUMN team_id INT NULL
AFTER template_name;
ALTER TABLE process_templates
ADD INDEX idx_team (team_id);
ALTER TABLE process_templates
ADD CONSTRAINT fk_template_team FOREIGN KEY (team_id) REFERENCES organization_units(id);
-- 7. 为 operations 添加 operation_type_id 外键
ALTER TABLE operations
ADD COLUMN operation_type_id INT NULL
AFTER operation_type;
ALTER TABLE operations
ADD CONSTRAINT fk_operation_type FOREIGN KEY (operation_type_id) REFERENCES operation_types(id);
-- 8. 迁移现有模板归属
UPDATE process_templates pt
SET team_id = (
        SELECT id
        FROM organization_units
        WHERE unit_code = 'USP'
    )
WHERE template_name IN ('WBP2486/B', 'WBP2486/B - backup', '长白夜班');
UPDATE process_templates pt
SET team_id = (
        SELECT id
        FROM organization_units
        WHERE unit_code = 'DSP'
    )
WHERE template_name = '下游';
-- 9. 为未指定的模板设置默认 USP
UPDATE process_templates
SET team_id = (
        SELECT id
        FROM organization_units
        WHERE unit_code = 'USP'
    )
WHERE team_id IS NULL;
-- 10. 迁移现有操作类型（保留原枚举值映射到新类型）
-- PREP -> BIOREACTOR_PREP, PROCESS -> CELL_CULTURE, MONITOR -> MONITORING
UPDATE operations o
    JOIN operation_types ot ON ot.type_code = CASE
        WHEN o.operation_type = 'PREP' THEN 'BIOREACTOR_PREP'
        WHEN o.operation_type = 'PROCESS' THEN 'CELL_CULTURE'
        WHEN o.operation_type = 'MONITOR' THEN 'MONITORING'
        ELSE 'CELL_CULTURE'
    END
    JOIN organization_units ou ON ot.team_id = ou.id
    AND ou.unit_code = 'USP'
SET o.operation_type_id = ot.id
WHERE o.operation_type_id IS NULL;