-- Phase 0A-1 constraint catalog and APS conflict persistence.
-- Do not run this file directly in shared environments.
-- Use scripts/phase0a/run_phase0a_migrations.ts, which preflights and skips existing objects.

CREATE TABLE IF NOT EXISTS constraint_definitions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  constraint_code VARCHAR(100) NOT NULL,
  constraint_name VARCHAR(255) NOT NULL,
  category ENUM(
    'FLOW_WINDOW',
    'QUALITY_GATE',
    'EQUIPMENT_STATE',
    'UTILITY_CAPACITY',
    'SPACE_SEGREGATION',
    'WORKFORCE_COVERAGE',
    'ROSTER_QUALIFICATION',
    'ROSTER_HANDOVER',
    'ROSTER_TRANSITION',
    'ROSTER_REST'
  ) NOT NULL,
  hard_or_soft_default ENUM('hard','soft') NOT NULL DEFAULT 'hard',
  default_severity ENUM('info','warning','critical') NOT NULL DEFAULT 'critical',
  violation_message_template VARCHAR(1000) NOT NULL,
  suggested_action_template VARCHAR(1000) NULL,
  owner_domain ENUM('APS','ROSTER','MASTER_DATA','GOVERNANCE','INTEGRATION') NOT NULL DEFAULT 'APS',
  lifecycle_status ENUM('DRAFT','ACTIVE','RETIRED') NOT NULL DEFAULT 'ACTIVE',
  effective_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  effective_to DATETIME NULL,
  planning_criticality ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'HIGH',
  quality_relevant TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_constraint_definitions_code (constraint_code),
  KEY idx_constraint_definitions_category (category),
  KEY idx_constraint_definitions_status (lifecycle_status, effective_from, effective_to),
  CONSTRAINT fk_constraint_definitions_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS aps_conflicts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  scenario_id BIGINT NOT NULL,
  constraint_code VARCHAR(100) NOT NULL,
  severity ENUM('info','warning','critical') NOT NULL,
  hard_or_soft ENUM('hard','soft') NOT NULL,
  entity_type VARCHAR(100) NULL,
  entity_id BIGINT NULL,
  batch_plan_id INT NULL,
  batch_operation_plan_id INT NULL,
  resource_id INT NULL,
  material_lot_id BIGINT NULL,
  time_window_start DATETIME NULL,
  time_window_end DATETIME NULL,
  violation_reason VARCHAR(2000) NOT NULL,
  suggested_action VARCHAR(2000) NULL,
  conflict_status ENUM('OPEN','ACKNOWLEDGED','WAIVED','RESOLVED','SUPERSEDED') NOT NULL DEFAULT 'OPEN',
  detected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  detected_by_run_id BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  resolved_by BIGINT NULL,
  resolution_reason VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_aps_conflicts_scenario_status (scenario_id, conflict_status),
  KEY idx_aps_conflicts_constraint (constraint_code),
  KEY idx_aps_conflicts_entity (entity_type, entity_id),
  KEY idx_aps_conflicts_batch (batch_plan_id, batch_operation_plan_id),
  KEY idx_aps_conflicts_resource (resource_id),
  KEY idx_aps_conflicts_time (time_window_start, time_window_end),
  KEY idx_aps_conflicts_run (detected_by_run_id),
  CONSTRAINT fk_aps_conflicts_scenario FOREIGN KEY (scenario_id) REFERENCES aps_scenarios(id),
  CONSTRAINT fk_aps_conflicts_constraint FOREIGN KEY (constraint_code) REFERENCES constraint_definitions(constraint_code),
  CONSTRAINT fk_aps_conflicts_batch_plan FOREIGN KEY (batch_plan_id) REFERENCES production_batch_plans(id),
  CONSTRAINT fk_aps_conflicts_batch_operation FOREIGN KEY (batch_operation_plan_id) REFERENCES batch_operation_plans(id),
  CONSTRAINT fk_aps_conflicts_resource FOREIGN KEY (resource_id) REFERENCES resources(id),
  CONSTRAINT fk_aps_conflicts_run FOREIGN KEY (detected_by_run_id) REFERENCES scheduling_runs(id),
  CONSTRAINT fk_aps_conflicts_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO constraint_definitions
(constraint_code, constraint_name, category, hard_or_soft_default, default_severity,
 violation_message_template, suggested_action_template, owner_domain, lifecycle_status, planning_criticality, quality_relevant)
VALUES
('FLOW_OPERATION_DEPENDENCY', 'Operation dependency violation', 'FLOW_WINDOW', 'hard', 'critical',
 'Operation {successor} violates dependency from {predecessor}; expected window {expected_window}, actual {actual_window}.',
 'Adjust scenario timing or mark scenario infeasible; do not auto-shift silently.', 'APS', 'ACTIVE', 'HIGH', 0),
('FLOW_MAX_HOLD_EXCEEDED', 'Maximum hold time exceeded', 'FLOW_WINDOW', 'hard', 'critical',
 'Hold time between {from_operation} and {to_operation} exceeds {max_hold}.',
 'Review batch timing, material/equipment hold state, or mark infeasible.', 'APS', 'ACTIVE', 'HIGH', 0),
('QUALITY_QC_EXTERNAL_STATUS_NOT_READY', 'QC/QA external status not ready', 'QUALITY_GATE', 'hard', 'critical',
 'Downstream operation {operation} has planning risk because external QC/QA status reference {gate} is not ready.',
 'Review external status reference or revise the planning scenario.', 'APS', 'ACTIVE', 'HIGH', 1),
('EQUIPMENT_NO_OVERLAP', 'Equipment no-overlap violation', 'EQUIPMENT_STATE', 'hard', 'critical',
 'Resource {resource} is assigned to overlapping operations in scenario {scenario}.',
 'Select another resource or revise operation timing.', 'APS', 'ACTIVE', 'HIGH', 0),
('SPACE_SUITE_NO_OVERLAP', 'Suite no-overlap violation', 'SPACE_SEGREGATION', 'hard', 'critical',
 'Suite {suite} has overlapping occupancy in scenario {scenario}.',
 'Resolve suite occupancy or split scenario.', 'APS', 'ACTIVE', 'HIGH', 0),
('WORKFORCE_SKILL_DEMAND_NOT_COVERED', 'Skill demand not covered', 'WORKFORCE_COVERAGE', 'hard', 'critical',
 'Skill demand {skill} requires {required_count}; roster capacity is {available_count}.',
 'Request roster replan or revise APS scenario.', 'APS', 'ACTIVE', 'HIGH', 0);
