-- Phase 0A-1 recipe/campaign/snapshot schema.
-- Do not run this file directly in shared environments.
-- Use scripts/phase0a/run_phase0a_migrations.ts, which preflights and skips existing objects.

CREATE TABLE IF NOT EXISTS products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_code VARCHAR(100) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  molecule_name VARCHAR(255) NULL,
  product_family VARCHAR(120) NULL,
  modality VARCHAR(120) NULL,
  default_scale_liters DECIMAL(12,2) NULL,
  status ENUM('ACTIVE','INACTIVE','RETIRED') NOT NULL DEFAULT 'ACTIVE',
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_products_code (product_code),
  KEY idx_products_status (status),
  CONSTRAINT fk_products_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recipe_versions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT NOT NULL,
  recipe_code VARCHAR(100) NOT NULL,
  recipe_name VARCHAR(255) NOT NULL,
  version_no VARCHAR(50) NOT NULL,
  scale_liters DECIMAL(12,2) NULL,
  lifecycle_status ENUM('DRAFT','APPROVED','EFFECTIVE','RETIRED') NOT NULL DEFAULT 'DRAFT',
  effective_from DATETIME NULL,
  effective_to DATETIME NULL,
  source_template_id INT NULL,
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_recipe_versions_code_version (recipe_code, version_no),
  KEY idx_recipe_versions_product_status (product_id, lifecycle_status),
  KEY idx_recipe_versions_template (source_template_id),
  CONSTRAINT fk_recipe_versions_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_recipe_versions_source_template FOREIGN KEY (source_template_id) REFERENCES process_templates(id),
  CONSTRAINT fk_recipe_versions_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_recipe_versions_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recipe_unit_operations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipe_version_id BIGINT NOT NULL,
  unit_op_code VARCHAR(100) NOT NULL,
  unit_op_name VARCHAR(255) NOT NULL,
  sequence_no INT NOT NULL,
  process_area ENUM('USP','DSP','SPI','QC','QA','WAREHOUSE','ENGINEERING','ANCILLARY') NOT NULL,
  semantic_type VARCHAR(100) NULL,
  default_duration_minutes INT NULL,
  min_duration_minutes INT NULL,
  max_duration_minutes INT NULL,
  earliest_offset_minutes INT NULL,
  latest_offset_minutes INT NULL,
  hold_time_limit_minutes INT NULL,
  requires_qc_status_ready TINYINT(1) NOT NULL DEFAULT 0,
  is_continuous TINYINT(1) NOT NULL DEFAULT 0,
  is_biological_fixed_duration TINYINT(1) NOT NULL DEFAULT 0,
  required_people INT NULL,
  source_stage_operation_id INT NULL,
  operation_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_recipe_unit_operations_code (recipe_version_id, unit_op_code),
  KEY idx_recipe_unit_operations_sequence (recipe_version_id, sequence_no),
  KEY idx_recipe_unit_operations_area (process_area),
  KEY idx_recipe_unit_operations_source (source_stage_operation_id),
  CONSTRAINT fk_recipe_unit_operations_recipe FOREIGN KEY (recipe_version_id) REFERENCES recipe_versions(id),
  CONSTRAINT fk_recipe_unit_operations_source FOREIGN KEY (source_stage_operation_id) REFERENCES stage_operation_schedules(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS operation_dependencies (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipe_version_id BIGINT NOT NULL,
  predecessor_unit_op_id BIGINT NOT NULL,
  successor_unit_op_id BIGINT NOT NULL,
  dependency_type ENUM('FS','SS','FF','SF') NOT NULL DEFAULT 'FS',
  lag_type ENUM('ASAP','FIXED','WINDOW','NEXT_DAY','NEXT_SHIFT','COOLING','BATCH_END','MAX_HOLD','ZERO_WAIT') NOT NULL DEFAULT 'ASAP',
  lag_min_minutes INT NULL,
  lag_max_minutes INT NULL,
  constraint_code VARCHAR(100) NOT NULL DEFAULT 'FLOW_OPERATION_DEPENDENCY',
  hard_or_soft ENUM('hard','soft') NOT NULL DEFAULT 'hard',
  severity ENUM('info','warning','critical') NOT NULL DEFAULT 'critical',
  dependency_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  source_operation_constraint_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_operation_dependencies_recipe (recipe_version_id),
  KEY idx_operation_dependencies_pred (predecessor_unit_op_id),
  KEY idx_operation_dependencies_succ (successor_unit_op_id),
  KEY idx_operation_dependencies_constraint (constraint_code),
  CONSTRAINT fk_operation_dependencies_recipe FOREIGN KEY (recipe_version_id) REFERENCES recipe_versions(id),
  CONSTRAINT fk_operation_dependencies_pred FOREIGN KEY (predecessor_unit_op_id) REFERENCES recipe_unit_operations(id),
  CONSTRAINT fk_operation_dependencies_succ FOREIGN KEY (successor_unit_op_id) REFERENCES recipe_unit_operations(id),
  CONSTRAINT fk_operation_dependencies_constraint FOREIGN KEY (constraint_code) REFERENCES constraint_definitions(constraint_code),
  CONSTRAINT fk_operation_dependencies_source FOREIGN KEY (source_operation_constraint_id) REFERENCES operation_constraints(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recipe_operation_skill_requirements (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recipe_version_id BIGINT NOT NULL,
  recipe_unit_operation_id BIGINT NOT NULL,
  qualification_id INT NULL,
  skill_code VARCHAR(120) NOT NULL,
  required_count INT NOT NULL DEFAULT 1,
  min_level INT NULL,
  area_code VARCHAR(80) NULL,
  product_scope VARCHAR(120) NULL,
  criticality ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'HIGH',
  requires_supervisor TINYINT(1) NOT NULL DEFAULT 0,
  requires_qa_on_floor TINYINT(1) NOT NULL DEFAULT 0,
  requires_two_person_verification TINYINT(1) NOT NULL DEFAULT 0,
  handover_overlap_minutes INT NOT NULL DEFAULT 0,
  gowning_minutes INT NOT NULL DEFAULT 0,
  requirement_status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  source_operation_qualification_requirement_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_recipe_skill_recipe (recipe_version_id),
  KEY idx_recipe_skill_operation (recipe_unit_operation_id),
  KEY idx_recipe_skill_qualification (qualification_id),
  KEY idx_recipe_skill_code (skill_code),
  CONSTRAINT fk_recipe_skill_recipe FOREIGN KEY (recipe_version_id) REFERENCES recipe_versions(id),
  CONSTRAINT fk_recipe_skill_operation FOREIGN KEY (recipe_unit_operation_id) REFERENCES recipe_unit_operations(id),
  CONSTRAINT fk_recipe_skill_qualification FOREIGN KEY (qualification_id) REFERENCES qualifications(id),
  CONSTRAINT fk_recipe_skill_source FOREIGN KEY (source_operation_qualification_requirement_id) REFERENCES operation_qualification_requirements(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  campaign_code VARCHAR(100) NOT NULL,
  campaign_name VARCHAR(255) NOT NULL,
  product_id BIGINT NOT NULL,
  recipe_version_id BIGINT NOT NULL,
  site_code VARCHAR(80) NULL,
  building_code VARCHAR(80) NULL,
  suite_group_code VARCHAR(80) NULL,
  target_batch_count INT NULL,
  planned_start DATETIME NOT NULL,
  planned_end DATETIME NOT NULL,
  campaign_status ENUM('DRAFT','APPROVED','SCHEDULED','PUBLISHED','CLOSED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  changeover_policy VARCHAR(120) NULL,
  created_by BIGINT NULL,
  approved_by BIGINT NULL,
  published_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at DATETIME NULL,
  published_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_campaigns_code (campaign_code),
  KEY idx_campaigns_product_start (product_id, planned_start),
  KEY idx_campaigns_recipe (recipe_version_id),
  KEY idx_campaigns_status (campaign_status),
  CONSTRAINT fk_campaigns_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_campaigns_recipe FOREIGN KEY (recipe_version_id) REFERENCES recipe_versions(id),
  CONSTRAINT fk_campaigns_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_campaigns_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
  CONSTRAINT fk_campaigns_published_by FOREIGN KEY (published_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MySQL >= 8.0.16 may enforce CHECK constraints. The hardened runner applies this conditionally.
-- ALTER TABLE campaigns ADD CONSTRAINT chk_campaigns_window CHECK (planned_start < planned_end);

CREATE TABLE IF NOT EXISTS batch_recipe_snapshots (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  batch_plan_id INT NOT NULL,
  recipe_version_id BIGINT NOT NULL,
  recipe_version_no VARCHAR(50) NOT NULL,
  snapshot_version INT NOT NULL DEFAULT 1,
  snapshot_json JSON NOT NULL,
  unit_operations_json JSON NOT NULL,
  dependencies_json JSON NOT NULL,
  bom_snapshot_json JSON NULL,
  snapshot_status ENUM('ACTIVE','SUPERSEDED') NOT NULL DEFAULT 'ACTIVE',
  snapshotted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  snapshotted_by BIGINT NULL,
  UNIQUE KEY uk_batch_recipe_snapshot_version (batch_plan_id, snapshot_version),
  KEY idx_batch_recipe_snapshots_batch (batch_plan_id),
  KEY idx_batch_recipe_snapshots_recipe (recipe_version_id),
  CONSTRAINT fk_batch_recipe_snapshots_batch FOREIGN KEY (batch_plan_id) REFERENCES production_batch_plans(id),
  CONSTRAINT fk_batch_recipe_snapshots_recipe FOREIGN KEY (recipe_version_id) REFERENCES recipe_versions(id),
  CONSTRAINT fk_batch_recipe_snapshots_by FOREIGN KEY (snapshotted_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS campaign_batches (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  campaign_id BIGINT NOT NULL,
  batch_plan_id INT NOT NULL,
  batch_sequence_no INT NOT NULL,
  batch_code VARCHAR(100) NOT NULL,
  planned_scale_liters DECIMAL(12,2) NULL,
  recipe_snapshot_id BIGINT NULL,
  batch_status ENUM('PLANNED','SCHEDULED','PUBLISHED','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_campaign_batches_sequence (campaign_id, batch_sequence_no),
  UNIQUE KEY uk_campaign_batches_batch_plan (batch_plan_id),
  KEY idx_campaign_batches_campaign (campaign_id),
  KEY idx_campaign_batches_snapshot (recipe_snapshot_id),
  CONSTRAINT fk_campaign_batches_campaign FOREIGN KEY (campaign_id) REFERENCES campaigns(id),
  CONSTRAINT fk_campaign_batches_batch FOREIGN KEY (batch_plan_id) REFERENCES production_batch_plans(id),
  CONSTRAINT fk_campaign_batches_snapshot FOREIGN KEY (recipe_snapshot_id) REFERENCES batch_recipe_snapshots(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
